env:
  es2020: true
extends:
  - react-app
  - react-app/jest
  - plugin:@typescript-eslint/recommended
  - plugin:jest/all
  - prettier
ignorePatterns:
  - build/
  - coverage/
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  project: ./tsconfig.json
  sourceType: module
plugins:
  - deprecation
  - sort-keys-fix
  - import
rules:
  comma-dangle:
    - error
    - always-multiline
  deprecation/deprecation:
    - error
  import/no-unresolved:
    - error
    - commonjs: true
  import/order:
    - error
    - alphabetize:
        order: asc
      groups:
        - builtin
        - external
        - - sibling
          - parent
        - index
      newlines-between: always
  no-console: error
  react/self-closing-comp: error
  react-hooks/exhaustive-deps:
    - error
    - additionalHooks: useObservable
  sort-keys-fix/sort-keys-fix: error
  '@typescript-eslint/no-floating-promises': error
  '@typescript-eslint/strict-boolean-expressions': error
  jest/lowercase-name:
    - error
    - ignore:
        - describe
settings:
  import/parsers:
    '@typescript-eslint/parser': [.ts, .tsx]
  import/resolver:
    typescript:
      alwaysTryTypes: true
